### ISSUE TITLE
compilation troublesome when using MinGW

### ISSUE THREAD

**Issue by Thelvaen** [godotjs/GodotJS#14]
Hello,

For technical reasons, I need to build using MinGW instead of MSVC. But compiling with MinGW instead of MSVC is not going "smoothly". Not being sure I could build the v8 libs against the target, I opted to use QuickJS which did not generate anything other than warnings once those couple of issues where "patched".

for example, in `weaver-editor/jsb_editor_macros.h`, MinGW doesn't like the `'` char in the #error statement
```
#error CAN NOT COMPILE WITHOUT TOOLS_ENABLED, PLEASE CHECK IT'S NOT UNEXPECTEDLY INCLUDED.
```

or in `internal/jsb_macros.h`, you might want to replace `#   define jsb_ensure(Condition) (void) (Condition)` with `#   define jsb_ensure(Condition) ((Condition) ? true : false)` (suggestion from ChatGPT when giving it the error message).

```
In file included from modules\GodotJS\impl\quickjs\jsb_quickjs_broker.cpp:2:
modules\GodotJS\impl\quickjs/jsb_quickjs_isolate.h:241:17: error: value of type 'void' is not contextually convertible to 'bool'
  241 |             if (jsb_ensure(it) && --it->value.watcher_ == 0)
      |                 ^~~~~~~~~~~~~~
modules\GodotJS\impl\quickjs/../../internal/jsb_macros.h:65:34: note: expanded from macro 'jsb_ensure'
   65 | #   define jsb_ensure(Condition) (void) (Condition)
      |                                  ^~~~~~~~~~~~~~~~~~
In file included from modules\GodotJS\impl\quickjs\jsb_quickjs_broker.cpp:2:
modules\GodotJS\impl\quickjs/jsb_quickjs_isolate.h:241:32: error: invalid operands to binary expression ('void' and 'bool')
  241 |             if (jsb_ensure(it) && --it->value.watcher_ == 0)
      |                 ~~~~~~~~~~~~
```

in `internal/jsb_sarrays.h`, I had to add:
```cpp
#include <cstddef>
-            TScopedPointer(nullptr_t) : container_(nullptr), ptr_(nullptr) { }
+            TScopedPointer(std::nullptr_t) : container_(nullptr), ptr_(nullptr) { }
-            TScopedPointer& operator=(nullptr_t)
+            TScopedPointer& operator=(std::nullptr_t)
```

**Comment by ialex32x** [comment]
Merged. I really appreciate your contribution. Thank you! 😊
