### ISSUE TITLE
using emit_signal with arguments throws an error

### ISSUE THREAD

**Issue by jkstrawn** [godotjs/GodotJS#25]
I'm running into an issue with calling `this.emit_signal` with arguments, it's always giving me a bad argument error. Maybe I'm doing something wrong? Based on the types, this seems to be the right way to do it. I get the same result with both signals added at runtime and signals defined in my C# scripts.

Simple example:
```
    _ready(): void {
        this.add_user_signal("MyCustomSignal");

        this.connect("MyCustomSignal", new Callable(this, "signalled"));

        this.emit_signal("MyCustomSignal"); // this will fire the signal correctly
        this.emit_signal("MyCustomSignal", "banana"); // this will throw a bad arguments error
    }

    signalled(from: string) {
        console.log("signalled from", from);
    }
```

The error:
```
E 0:00:00:0780   jsb::Environment::_call: [jsb][Error] exception thrown in function:
Uncaught Error: [modules\GodotJS\bridge\jsb_object_bindings.cpp:283 jsb::ObjectReflectBindingUtil::_godot_object_method] bad argument: 1
Error: [modules\GodotJS\bridge\jsb_object_bindings.cpp:283 jsb::ObjectReflectBindingUtil::_godot_object_method] bad argument: 1
    at DotnetBridgeTs._ready (res:\\dotnet\dotnetBridgeTS.ts:23:8)
  <C++ Source>   modules\GodotJS\bridge\jsb_environment.cpp:1185 @ jsb::Environment::_call()
```

I'm using a locally compiled Godot engine with latest from GodotJS and branch `4.3` from Godot source and mono enabled. If there's anything you could suggest I try, or any more information needed, I'm grateful!

**Comment by jkstrawn** [comment]
hmmm, I see that `add_user_signal` can take a second parameter as the arguments of the signal, but I can't figure out how it might want to be formatted. For reference, the C# function is organized as an array of dictionaries

```
Adds a user-defined signal. Optional arguments for the signal can be added as an Godot.Collections.Array of dictionaries, each defining a name string and a type int (see Variant.Type). See also GodotObject.HasUserSignal(StringName) and GodotObject.RemoveUserSignal(StringName).

AddUserSignal("Hurt", new Godot.Collections.Array()
{
    new Godot.Collections.Dictionary()
    {
        { "name", "damage" },
        { "type", (int)Variant.Type.Int }
    },
    new Godot.Collections.Dictionary()
    {
        { "name", "source" },
        { "type", (int)Variant.Type.Object }
    }
});
```

my best guess for the js equivalent is
```
        this.add_user_signal("MyCustomSignal", new GArray([
            new GDictionary({
                name: "from",
                type: Variant.Type.TYPE_STRING
            })
        ]));
```

but the GArray type keeps wanting it to match `PackedVector4Array`, and when I run the code anyways it gives another error:
```
E 0:00:00:0777   jsb::Environment::_call: [jsb][Error] exception thrown in function:
Uncaught Error: [modules\GodotJS\bridge\jsb_primitive_bindings_reflect.cpp:262] no suitable constructor
Error: [modules\GodotJS\bridge\jsb_primitive_bindings_reflect.cpp:262] no suitable constructor
    at DotnetBridgeTs._ready (res:\\dotnet\dotnetBridgeTS.ts:46:16)
  <C++ Source>   modules\GodotJS\bridge\jsb_environment.cpp:1185 @ jsb::Environment::_call()
```

**Comment by ialex32x** [comment]
Oh, sorry for the confusion, `add_user_signal` may not be supported yet (not sure, I'll check it later).
If you need to define a signal in your script class, try the `@signal` decorator. like this:
```ts
import { Signal, Signal1, Node } from "godot";
import { signal } from "jsb.core";

export default class MyScript extends Node {
    
    @signal()
    MyCustomSignal!: Signal1<string>; // use Signal0 if no parameter needed

    _ready() {
        
    }

   do_emit() {
        this.MyCustomSignal.emit("test");
    }
}

```

The decorated field `MyCustomSignal` will be initialized internally before `_ready`.

**Comment by jkstrawn** [comment]
Okay, thanks for the heads up.

My workaround right now is to create both the sending and receiving signals in the ts classes, and have my c# classes connect to the receiving signals, since the ts can't properly call the receiving signals if they're generated by the c# classes.

**Comment by ialex32x** [comment]
It's been fixed now. 
Godot returns a variant type from invalid memory address on calling `method_bind->get_argument_type(1)` for `emit_signal` (I reckon it's a bug of `get_argument_type` checking condition).

**Comment by jkstrawn** [comment]
Thank you!
